"""Sandboxed execution of generated extraction scripts.

NOTE: This is NOT a security sandbox. Python's exec() cannot be truly sandboxed.
The restricted builtins prevent accidental imports and limit surface area, but
scripts are generated by Claude API, not by untrusted external users.
"""

import builtins
from typing import Any

from .exceptions import ScriptExecutionError


_ALLOWED_BUILTIN_NAMES = {
    "len", "range", "str", "int", "float", "bool", "list", "dict", "tuple",
    "set", "enumerate", "zip", "map", "filter", "sorted", "reversed",
    "min", "max", "sum", "any", "all", "isinstance", "type",
    "None", "True", "False", "print", "repr", "abs", "round",
    "hasattr", "getattr", "KeyError", "ValueError", "TypeError",
    "IndexError", "AttributeError", "Exception", "StopIteration",
}


def _build_safe_builtins() -> dict:
    """Build a restricted __builtins__ dict."""
    safe = {}
    for name in _ALLOWED_BUILTIN_NAMES:
        obj = getattr(builtins, name, None)
        if obj is not None:
            safe[name] = obj
    return safe


async def execute_script(script_code: str, page: Any) -> Any:
    """Execute a generated extraction script in a sandboxed namespace.

    The script must define `async def extract(page) -> dict`.

    Args:
        script_code: Python source code containing an extract() function.
        page: A Playwright Page object (already navigated to the target URL).

    Returns:
        The result of calling extract(page).

    Raises:
        ScriptExecutionError: On compilation failure, missing extract function,
            or runtime error during extraction.
    """
    namespace = {"__builtins__": _build_safe_builtins()}

    try:
        exec(script_code, namespace)
    except SyntaxError as e:
        raise ScriptExecutionError(f"Script syntax error: {e}") from e
    except Exception as e:
        raise ScriptExecutionError(f"Script compilation failed: {e}") from e

    extract_fn = namespace.get("extract")
    if extract_fn is None or not callable(extract_fn):
        raise ScriptExecutionError(
            "Script does not define a callable 'extract' function"
        )

    try:
        result = await extract_fn(page)
    except Exception as e:
        raise ScriptExecutionError(
            f"Script execution failed: {type(e).__name__}: {e}"
        ) from e

    return result
